const head2 = document.querySelector("h2.sol3");
head2.addEventListener("click", function(){           //lepiej przypisać funkcję do zmiennej
	const div = document.createElement("div");
	div.setAttribute("class", "container");
	document.body.appendChild(div);
	const innerDiv = document.createElement("div");
	innerDiv.setAttribute("class", "item");
	div.appendChild(innerDiv);
	const innerDiv2 = document.createElement("div");
	innerDiv2.setAttribute("class", "item");
	div.appendChild(innerDiv2);
	const innerDiv3 = document.createElement("div");
	innerDiv3.setAttribute("class", "item");
	div.appendChild(innerDiv3);
	const innerDiv4 = document.createElement("div");
	innerDiv4.setAttribute("class", "item");
	div.appendChild(innerDiv4);
	const innerDiv5 = document.createElement("div");
	innerDiv5.setAttribute("class", "item");
	div.appendChild(innerDiv5);
	const innerDiv6 = document.createElement("div");
	innerDiv6.setAttribute("class", "item");
	div.appendChild(innerDiv6);
	const innerDiv7 = document.createElement("div");
	innerDiv7.setAttribute("class", "item");
	div.appendChild(innerDiv7);
	const innerDiv8 = document.createElement("div");
	innerDiv8.setAttribute("class", "item");
	div.appendChild(innerDiv8);
	const innerDiv9 = document.createElement("div");
	innerDiv9.setAttribute("class", "item");
	div.appendChild(innerDiv9);
	const innerDiv10 = document.createElement("div");
	innerDiv10.setAttribute("class", "item");
	div.appendChild(innerDiv10);
	const innerDiv11 = document.createElement("div");
	innerDiv11.setAttribute("class", "item");
	div.appendChild(innerDiv11);
	const innerDiv12 = document.createElement("div");
	innerDiv12.setAttribute("class", "item");
	div.appendChild(innerDiv12);
	const innerDiv13 = document.createElement("div");
	innerDiv13.setAttribute("class", "item");
	div.appendChild(innerDiv13);
	const innerDiv14 = document.createElement("div");
	innerDiv14.setAttribute("class", "item");
	div.appendChild(innerDiv14);
	const innerDiv15 = document.createElement("div");
	innerDiv15.setAttribute("class", "item");
	div.appendChild(innerDiv15);
	const innerDiv16 = document.createElement("div");
	innerDiv16.setAttribute("class", "item");
	div.appendChild(innerDiv16);
	const innerDiv17 = document.createElement("div");
	innerDiv17.setAttribute("class", "item");
	div.appendChild(innerDiv17);
	const innerDiv18 = document.createElement("div");
	innerDiv18.setAttribute("class", "item");
	div.appendChild(innerDiv18);
	const innerDiv19 = document.createElement("div");
	innerDiv19.setAttribute("class", "item");
	div.appendChild(innerDiv19);
	const innerDiv20 = document.createElement("div");
	innerDiv20.setAttribute("class", "item");
	div.appendChild(innerDiv20);
	const innerDiv21 = document.createElement("div");
	innerDiv21.setAttribute("class", "item");
	div.appendChild(innerDiv21);
	const innerDiv22 = document.createElement("div");
	innerDiv22.setAttribute("class", "item");
	div.appendChild(innerDiv22);
	const innerDiv23 = document.createElement("div");
	innerDiv23.setAttribute("class", "item");
	div.appendChild(innerDiv23);
	const innerDiv24 = document.createElement("div");
	innerDiv24.setAttribute("class", "item");
	div.appendChild(innerDiv24);
	const innerDiv25 = document.createElement("div");
	innerDiv25.setAttribute("class", "item");
	div.appendChild(innerDiv25);
});